name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-activate-base: false
        python-version: 3.10  # Set Python version

    - name: Create or update Conda environment
      run: |
        conda env update --file environment.yml --name base

    - name: Activate Conda environment
      run: |
        source activate base
        conda list  # Verify environment setup

    - name: Lint with flake8
      run: |
        source activate base
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source activate base
        pytest
